version: '3.6'

services:
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
    ports:
      - ${POSTGRES_OUTPUT_PORT}:${POSTGRES_PORT}
    volumes:
          - datapg:/var/lib/postgresql/data
volumes:
  datapg: